# Copyright 2025 Sophie Lund
#
# This file is part of DX Scripts.
#
# DX Scripts is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# DX Scripts is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with DX Scripts. If not,
# see <https://www.gnu.org/licenses/>.

site_name: DX Scripts
repo_url: https://github.com/sophie-lund/dx-scripts
repo_name: sophie-lund/dx-scripts

docs_dir: book

theme:
    name: material
    palette:
        scheme: slate
        primary: black
        accent: blue
    icon:
        repo: fontawesome/brands/github
    features:
        - content.code.copy
        - navigation.tabs

extra_css:
    - custom.css

extra:
    generator: false

plugins:
    - search

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - toc:
          permalink: true
    - admonition
    - pymdownx.tabbed:
          alternate_style: true
    - footnotes

nav:
    - Intro: index.md
    - Tutorial:
        - Adding to your project: tutorial/adding-to-your-project.md
    - Reference:
        - Recommended script structure: reference/recommended-script-structure.md
        - Logging: reference/logging.md
        - Prompts: reference/prompts.md
        - Utilities: reference/utilities.md
        - Config: reference/config.md
        - DNS: reference/dns.md
        - Docker: reference/docker.md
        - AWS: reference/aws.md
        - Dependency predicates: reference/dependency-predicates.md
        - Dependencies: reference/dependencies.md
        - Bootstrap: reference/bootstrap.md
        - C++: reference/cxx.md
        - Environment variables: reference/environment-variables.md
