name: Verify

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  bootstrap:
    name: Bootstrap
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bootstrap
        run: |
          DX_SCRIPTS_ALWAYS_CONSENT=true DX_SCRIPTS_DISABLE_BOOTSTRAP_UPGRADE=true bash ./bootstrap.bash

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: bootstrap

    steps:
      - name: Lint
        run: |
          just lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: bootstrap

    steps:
      - name: Test
        run: |
          just test-all
